version: '3'
services:
    database:
        image: postgres
        restart: always
        ports:
            - "5432:5432"
        env_file:
            - ./src/main/resources/.env
        volumes:
            - database-dev:/var/lib/postgresql/data
        healthcheck:
            test: "exit 0"
        networks:
            - apps-network

    pgadmin:
        image: dpage/pgadmin4
        restart: always
        env_file:
            - ./src/main/resources/.env
        ports:
            - "5050:80"
        networks:
            - apps-network
        depends_on:
            database:
                condition: service_healthy

    backend:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
        networks:
            - apps-network
        depends_on:
            database:
                condition: service_healthy

    keycloak:
        image: jboss/keycloak
        env_file:
            - ./src/main/resources/.env
        volumes:
            - keycloak-dev:/opt/jboss/keycloak/standalone/data
        ports:
            - "8180:8080"
        networks:
            - apps-network
        depends_on:
            database:
                condition: service_healthy

networks:
    apps-network:
        driver: bridge

volumes:
    database-dev:
        driver: local
    keycloak-dev:
        driver: local