/*
 * This file is generated by jOOQ.
 */
package com.dybek.timeme.domain.jooq.tables.pojos;


import java.io.Serializable;
import java.util.Arrays;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WorkspaceUser implements Serializable {

    private static final long serialVersionUID = 1L;

    private UUID     id;
    private String   nickname;
    private Object[] roles;
    private UUID     userId;
    private UUID     workspaceId;

    public WorkspaceUser() {}

    public WorkspaceUser(WorkspaceUser value) {
        this.id = value.id;
        this.nickname = value.nickname;
        this.roles = value.roles;
        this.userId = value.userId;
        this.workspaceId = value.workspaceId;
    }

    public WorkspaceUser(
        UUID     id,
        String   nickname,
        Object[] roles,
        UUID     userId,
        UUID     workspaceId
    ) {
        this.id = id;
        this.nickname = nickname;
        this.roles = roles;
        this.userId = userId;
        this.workspaceId = workspaceId;
    }

    /**
     * Getter for <code>workspace_user.id</code>.
     */
    public UUID getId() {
        return this.id;
    }

    /**
     * Setter for <code>workspace_user.id</code>.
     */
    public void setId(UUID id) {
        this.id = id;
    }

    /**
     * Getter for <code>workspace_user.nickname</code>.
     */
    public String getNickname() {
        return this.nickname;
    }

    /**
     * Setter for <code>workspace_user.nickname</code>.
     */
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    /**
     * Getter for <code>workspace_user.roles</code>.
     */
    public Object[] getRoles() {
        return this.roles;
    }

    /**
     * Setter for <code>workspace_user.roles</code>.
     */
    public void setRoles(Object[] roles) {
        this.roles = roles;
    }

    /**
     * Getter for <code>workspace_user.user_id</code>.
     */
    public UUID getUserId() {
        return this.userId;
    }

    /**
     * Setter for <code>workspace_user.user_id</code>.
     */
    public void setUserId(UUID userId) {
        this.userId = userId;
    }

    /**
     * Getter for <code>workspace_user.workspace_id</code>.
     */
    public UUID getWorkspaceId() {
        return this.workspaceId;
    }

    /**
     * Setter for <code>workspace_user.workspace_id</code>.
     */
    public void setWorkspaceId(UUID workspaceId) {
        this.workspaceId = workspaceId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("WorkspaceUser (");

        sb.append(id);
        sb.append(", ").append(nickname);
        sb.append(", ").append(Arrays.toString(roles));
        sb.append(", ").append(userId);
        sb.append(", ").append(workspaceId);

        sb.append(")");
        return sb.toString();
    }
}
