/*
 * This file is generated by jOOQ.
 */
package com.dybek.timeme.datasource.domain.tables;


import com.dybek.timeme.datasource.domain.DefaultSchema;
import com.dybek.timeme.datasource.domain.Keys;
import com.dybek.timeme.datasource.domain.tables.records.TaskRecord;

import java.util.Arrays;
import java.util.List;
import java.util.UUID;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Task extends TableImpl<TaskRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>task</code>
     */
    public static final Task TASK = new Task();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TaskRecord> getRecordType() {
        return TaskRecord.class;
    }

    /**
     * The column <code>task.id</code>.
     */
    public final TableField<TaskRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>task.workspace_user_id</code>.
     */
    public final TableField<TaskRecord, UUID> WORKSPACE_USER_ID = createField(DSL.name("workspace_user_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>task.workspace_id</code>.
     */
    public final TableField<TaskRecord, UUID> WORKSPACE_ID = createField(DSL.name("workspace_id"), SQLDataType.UUID.nullable(false), this, "");

    private Task(Name alias, Table<TaskRecord> aliased) {
        this(alias, aliased, null);
    }

    private Task(Name alias, Table<TaskRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>task</code> table reference
     */
    public Task(String alias) {
        this(DSL.name(alias), TASK);
    }

    /**
     * Create an aliased <code>task</code> table reference
     */
    public Task(Name alias) {
        this(alias, TASK);
    }

    /**
     * Create a <code>task</code> table reference
     */
    public Task() {
        this(DSL.name("task"), null);
    }

    public <O extends Record> Task(Table<O> child, ForeignKey<O, TaskRecord> key) {
        super(child, key, TASK);
    }

    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public UniqueKey<TaskRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_363;
    }

    @Override
    public List<UniqueKey<TaskRecord>> getKeys() {
        return Arrays.<UniqueKey<TaskRecord>>asList(Keys.CONSTRAINT_363);
    }

    @Override
    public List<ForeignKey<TaskRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<TaskRecord, ?>>asList(Keys.CONSTRAINT_3, Keys.CONSTRAINT_36);
    }

    private transient WorkspaceUser _workspaceUser;
    private transient Workspace _workspace;

    public WorkspaceUser workspaceUser() {
        if (_workspaceUser == null)
            _workspaceUser = new WorkspaceUser(this, Keys.CONSTRAINT_3);

        return _workspaceUser;
    }

    public Workspace workspace() {
        if (_workspace == null)
            _workspace = new Workspace(this, Keys.CONSTRAINT_36);

        return _workspace;
    }

    @Override
    public Task as(String alias) {
        return new Task(DSL.name(alias), this);
    }

    @Override
    public Task as(Name alias) {
        return new Task(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Task rename(String name) {
        return new Task(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Task rename(Name name) {
        return new Task(name, null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<UUID, UUID, UUID> fieldsRow() {
        return (Row3) super.fieldsRow();
    }
}
