/*
 * This file is generated by jOOQ.
 */
package com.dybek.timeme.datasource.domain.tables.pojos;


import java.io.Serializable;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Task implements Serializable {

    private static final long serialVersionUID = 1L;

    private UUID id;
    private UUID workspaceUserId;
    private UUID workspaceId;

    public Task() {}

    public Task(Task value) {
        this.id = value.id;
        this.workspaceUserId = value.workspaceUserId;
        this.workspaceId = value.workspaceId;
    }

    public Task(
        UUID id,
        UUID workspaceUserId,
        UUID workspaceId
    ) {
        this.id = id;
        this.workspaceUserId = workspaceUserId;
        this.workspaceId = workspaceId;
    }

    /**
     * Getter for <code>task.id</code>.
     */
    public UUID getId() {
        return this.id;
    }

    /**
     * Setter for <code>task.id</code>.
     */
    public void setId(UUID id) {
        this.id = id;
    }

    /**
     * Getter for <code>task.workspace_user_id</code>.
     */
    public UUID getWorkspaceUserId() {
        return this.workspaceUserId;
    }

    /**
     * Setter for <code>task.workspace_user_id</code>.
     */
    public void setWorkspaceUserId(UUID workspaceUserId) {
        this.workspaceUserId = workspaceUserId;
    }

    /**
     * Getter for <code>task.workspace_id</code>.
     */
    public UUID getWorkspaceId() {
        return this.workspaceId;
    }

    /**
     * Setter for <code>task.workspace_id</code>.
     */
    public void setWorkspaceId(UUID workspaceId) {
        this.workspaceId = workspaceId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Task (");

        sb.append(id);
        sb.append(", ").append(workspaceUserId);
        sb.append(", ").append(workspaceId);

        sb.append(")");
        return sb.toString();
    }
}
