/*
 * This file is generated by jOOQ.
 */
package com.dybek.timeme.datasource.domain.tables.pojos;


import java.io.Serializable;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Workspace implements Serializable {

    private static final long serialVersionUID = 1L;

    private UUID id;

    public Workspace() {}

    public Workspace(Workspace value) {
        this.id = value.id;
    }

    public Workspace(
        UUID id
    ) {
        this.id = id;
    }

    /**
     * Getter for <code>workspace.id</code>.
     */
    public UUID getId() {
        return this.id;
    }

    /**
     * Setter for <code>workspace.id</code>.
     */
    public void setId(UUID id) {
        this.id = id;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Workspace (");

        sb.append(id);

        sb.append(")");
        return sb.toString();
    }
}
