/*
 * This file is generated by jOOQ.
 */
package com.dybek.timeme.domain.jooq.tables.records;


import com.dybek.timeme.domain.jooq.tables.Task;

import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TaskRecord extends UpdatableRecordImpl<TaskRecord> implements Record4<UUID, String, UUID, UUID> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>task.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>task.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>task.title</code>.
     */
    public void setTitle(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>task.title</code>.
     */
    public String getTitle() {
        return (String) get(1);
    }

    /**
     * Setter for <code>task.workspace_user_id</code>.
     */
    public void setWorkspaceUserId(UUID value) {
        set(2, value);
    }

    /**
     * Getter for <code>task.workspace_user_id</code>.
     */
    public UUID getWorkspaceUserId() {
        return (UUID) get(2);
    }

    /**
     * Setter for <code>task.workspace_id</code>.
     */
    public void setWorkspaceId(UUID value) {
        set(3, value);
    }

    /**
     * Getter for <code>task.workspace_id</code>.
     */
    public UUID getWorkspaceId() {
        return (UUID) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<UUID, String, UUID, UUID> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<UUID, String, UUID, UUID> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return Task.TASK.ID;
    }

    @Override
    public Field<String> field2() {
        return Task.TASK.TITLE;
    }

    @Override
    public Field<UUID> field3() {
        return Task.TASK.WORKSPACE_USER_ID;
    }

    @Override
    public Field<UUID> field4() {
        return Task.TASK.WORKSPACE_ID;
    }

    @Override
    public UUID component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getTitle();
    }

    @Override
    public UUID component3() {
        return getWorkspaceUserId();
    }

    @Override
    public UUID component4() {
        return getWorkspaceId();
    }

    @Override
    public UUID value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getTitle();
    }

    @Override
    public UUID value3() {
        return getWorkspaceUserId();
    }

    @Override
    public UUID value4() {
        return getWorkspaceId();
    }

    @Override
    public TaskRecord value1(UUID value) {
        setId(value);
        return this;
    }

    @Override
    public TaskRecord value2(String value) {
        setTitle(value);
        return this;
    }

    @Override
    public TaskRecord value3(UUID value) {
        setWorkspaceUserId(value);
        return this;
    }

    @Override
    public TaskRecord value4(UUID value) {
        setWorkspaceId(value);
        return this;
    }

    @Override
    public TaskRecord values(UUID value1, String value2, UUID value3, UUID value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TaskRecord
     */
    public TaskRecord() {
        super(Task.TASK);
    }

    /**
     * Create a detached, initialised TaskRecord
     */
    public TaskRecord(UUID id, String title, UUID workspaceUserId, UUID workspaceId) {
        super(Task.TASK);

        setId(id);
        setTitle(title);
        setWorkspaceUserId(workspaceUserId);
        setWorkspaceId(workspaceId);
    }
}
