/*
 * This file is generated by jOOQ.
 */
package com.dybek.timeme.datasource.domain;


import com.dybek.timeme.datasource.domain.tables.Task;
import com.dybek.timeme.datasource.domain.tables.Workspace;
import com.dybek.timeme.datasource.domain.tables.WorkspaceUser;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DefaultSchema extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>DEFAULT_SCHEMA</code>
     */
    public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();

    /**
     * The table <code>task</code>.
     */
    public final Task TASK = Task.TASK;

    /**
     * The table <code>workspace</code>.
     */
    public final Workspace WORKSPACE = Workspace.WORKSPACE;

    /**
     * The table <code>workspace_user</code>.
     */
    public final WorkspaceUser WORKSPACE_USER = WorkspaceUser.WORKSPACE_USER;

    /**
     * No further instances allowed
     */
    private DefaultSchema() {
        super("", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            Task.TASK,
            Workspace.WORKSPACE,
            WorkspaceUser.WORKSPACE_USER);
    }
}
