/*
 * This file is generated by jOOQ.
 */
package com.dybek.timeme.domain.jooq;


import com.dybek.timeme.domain.jooq.tables.Task;
import com.dybek.timeme.domain.jooq.tables.Workspace;
import com.dybek.timeme.domain.jooq.tables.WorkspaceUser;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>task</code>.
     */
    public static final Task TASK = Task.TASK;

    /**
     * The table <code>workspace</code>.
     */
    public static final Workspace WORKSPACE = Workspace.WORKSPACE;

    /**
     * The table <code>workspace_user</code>.
     */
    public static final WorkspaceUser WORKSPACE_USER = WorkspaceUser.WORKSPACE_USER;
}
