/*
 * This file is generated by jOOQ.
 */
package com.dybek.timeme.domain.jooq.tables.daos;


import com.dybek.timeme.domain.jooq.tables.Workspace;
import com.dybek.timeme.domain.jooq.tables.records.WorkspaceRecord;

import java.util.List;
import java.util.UUID;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WorkspaceDao extends DAOImpl<WorkspaceRecord, com.dybek.timeme.domain.jooq.tables.pojos.Workspace, UUID> {

    /**
     * Create a new WorkspaceDao without any configuration
     */
    public WorkspaceDao() {
        super(Workspace.WORKSPACE, com.dybek.timeme.domain.jooq.tables.pojos.Workspace.class);
    }

    /**
     * Create a new WorkspaceDao with an attached configuration
     */
    public WorkspaceDao(Configuration configuration) {
        super(Workspace.WORKSPACE, com.dybek.timeme.domain.jooq.tables.pojos.Workspace.class, configuration);
    }

    @Override
    public UUID getId(com.dybek.timeme.domain.jooq.tables.pojos.Workspace object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.dybek.timeme.domain.jooq.tables.pojos.Workspace> fetchRangeOfId(UUID lowerInclusive, UUID upperInclusive) {
        return fetchRange(Workspace.WORKSPACE.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.dybek.timeme.domain.jooq.tables.pojos.Workspace> fetchById(UUID... values) {
        return fetch(Workspace.WORKSPACE.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.dybek.timeme.domain.jooq.tables.pojos.Workspace fetchOneById(UUID value) {
        return fetchOne(Workspace.WORKSPACE.ID, value);
    }
}
