/*
 * This file is generated by jOOQ.
 */
package com.dybek.timeme.domain.jooq.tables.daos;


import com.dybek.timeme.domain.jooq.tables.WorkspaceUser;
import com.dybek.timeme.domain.jooq.tables.records.WorkspaceUserRecord;

import java.util.List;
import java.util.UUID;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WorkspaceUserDao extends DAOImpl<WorkspaceUserRecord, com.dybek.timeme.domain.jooq.tables.pojos.WorkspaceUser, UUID> {

    /**
     * Create a new WorkspaceUserDao without any configuration
     */
    public WorkspaceUserDao() {
        super(WorkspaceUser.WORKSPACE_USER, com.dybek.timeme.domain.jooq.tables.pojos.WorkspaceUser.class);
    }

    /**
     * Create a new WorkspaceUserDao with an attached configuration
     */
    public WorkspaceUserDao(Configuration configuration) {
        super(WorkspaceUser.WORKSPACE_USER, com.dybek.timeme.domain.jooq.tables.pojos.WorkspaceUser.class, configuration);
    }

    @Override
    public UUID getId(com.dybek.timeme.domain.jooq.tables.pojos.WorkspaceUser object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.dybek.timeme.domain.jooq.tables.pojos.WorkspaceUser> fetchRangeOfId(UUID lowerInclusive, UUID upperInclusive) {
        return fetchRange(WorkspaceUser.WORKSPACE_USER.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.dybek.timeme.domain.jooq.tables.pojos.WorkspaceUser> fetchById(UUID... values) {
        return fetch(WorkspaceUser.WORKSPACE_USER.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.dybek.timeme.domain.jooq.tables.pojos.WorkspaceUser fetchOneById(UUID value) {
        return fetchOne(WorkspaceUser.WORKSPACE_USER.ID, value);
    }

    /**
     * Fetch records that have <code>nickname BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.dybek.timeme.domain.jooq.tables.pojos.WorkspaceUser> fetchRangeOfNickname(String lowerInclusive, String upperInclusive) {
        return fetchRange(WorkspaceUser.WORKSPACE_USER.NICKNAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>nickname IN (values)</code>
     */
    public List<com.dybek.timeme.domain.jooq.tables.pojos.WorkspaceUser> fetchByNickname(String... values) {
        return fetch(WorkspaceUser.WORKSPACE_USER.NICKNAME, values);
    }

    /**
     * Fetch records that have <code>roles BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.dybek.timeme.domain.jooq.tables.pojos.WorkspaceUser> fetchRangeOfRoles(Object[] lowerInclusive, Object[] upperInclusive) {
        return fetchRange(WorkspaceUser.WORKSPACE_USER.ROLES, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>roles IN (values)</code>
     */
    public List<com.dybek.timeme.domain.jooq.tables.pojos.WorkspaceUser> fetchByRoles(Object[]... values) {
        return fetch(WorkspaceUser.WORKSPACE_USER.ROLES, values);
    }

    /**
     * Fetch records that have <code>user_id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.dybek.timeme.domain.jooq.tables.pojos.WorkspaceUser> fetchRangeOfUserId(UUID lowerInclusive, UUID upperInclusive) {
        return fetchRange(WorkspaceUser.WORKSPACE_USER.USER_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>user_id IN (values)</code>
     */
    public List<com.dybek.timeme.domain.jooq.tables.pojos.WorkspaceUser> fetchByUserId(UUID... values) {
        return fetch(WorkspaceUser.WORKSPACE_USER.USER_ID, values);
    }

    /**
     * Fetch records that have <code>workspace_id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.dybek.timeme.domain.jooq.tables.pojos.WorkspaceUser> fetchRangeOfWorkspaceId(UUID lowerInclusive, UUID upperInclusive) {
        return fetchRange(WorkspaceUser.WORKSPACE_USER.WORKSPACE_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>workspace_id IN (values)</code>
     */
    public List<com.dybek.timeme.domain.jooq.tables.pojos.WorkspaceUser> fetchByWorkspaceId(UUID... values) {
        return fetch(WorkspaceUser.WORKSPACE_USER.WORKSPACE_ID, values);
    }
}
