/*
 * This file is generated by jOOQ.
 */
package com.dybek.timeme.domain.tables.records;


import com.dybek.timeme.domain.tables.Workspace;

import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Row1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WorkspaceRecord extends UpdatableRecordImpl<WorkspaceRecord> implements Record1<UUID> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>workspace.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>workspace.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record1 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row1<UUID> fieldsRow() {
        return (Row1) super.fieldsRow();
    }

    @Override
    public Row1<UUID> valuesRow() {
        return (Row1) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return Workspace.WORKSPACE.ID;
    }

    @Override
    public UUID component1() {
        return getId();
    }

    @Override
    public UUID value1() {
        return getId();
    }

    @Override
    public WorkspaceRecord value1(UUID value) {
        setId(value);
        return this;
    }

    @Override
    public WorkspaceRecord values(UUID value1) {
        value1(value1);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached WorkspaceRecord
     */
    public WorkspaceRecord() {
        super(Workspace.WORKSPACE);
    }

    /**
     * Create a detached, initialised WorkspaceRecord
     */
    public WorkspaceRecord(UUID id) {
        super(Workspace.WORKSPACE);

        setId(id);
    }
}
