/*
 * This file is generated by jOOQ.
 */
package com.dybek.timeme.domain.tables.records;


import com.dybek.timeme.domain.tables.WorkspaceUser;

import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WorkspaceUserRecord extends UpdatableRecordImpl<WorkspaceUserRecord> implements Record5<UUID, String, Object[], UUID, UUID> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>workspace_user.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>workspace_user.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>workspace_user.nickname</code>.
     */
    public void setNickname(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>workspace_user.nickname</code>.
     */
    public String getNickname() {
        return (String) get(1);
    }

    /**
     * Setter for <code>workspace_user.roles</code>.
     */
    public void setRoles(Object[] value) {
        set(2, value);
    }

    /**
     * Getter for <code>workspace_user.roles</code>.
     */
    public Object[] getRoles() {
        return (Object[]) get(2);
    }

    /**
     * Setter for <code>workspace_user.user_id</code>.
     */
    public void setUserId(UUID value) {
        set(3, value);
    }

    /**
     * Getter for <code>workspace_user.user_id</code>.
     */
    public UUID getUserId() {
        return (UUID) get(3);
    }

    /**
     * Setter for <code>workspace_user.workspace_id</code>.
     */
    public void setWorkspaceId(UUID value) {
        set(4, value);
    }

    /**
     * Getter for <code>workspace_user.workspace_id</code>.
     */
    public UUID getWorkspaceId() {
        return (UUID) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<UUID, String, Object[], UUID, UUID> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<UUID, String, Object[], UUID, UUID> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return WorkspaceUser.WORKSPACE_USER.ID;
    }

    @Override
    public Field<String> field2() {
        return WorkspaceUser.WORKSPACE_USER.NICKNAME;
    }

    @Override
    public Field<Object[]> field3() {
        return WorkspaceUser.WORKSPACE_USER.ROLES;
    }

    @Override
    public Field<UUID> field4() {
        return WorkspaceUser.WORKSPACE_USER.USER_ID;
    }

    @Override
    public Field<UUID> field5() {
        return WorkspaceUser.WORKSPACE_USER.WORKSPACE_ID;
    }

    @Override
    public UUID component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getNickname();
    }

    @Override
    public Object[] component3() {
        return getRoles();
    }

    @Override
    public UUID component4() {
        return getUserId();
    }

    @Override
    public UUID component5() {
        return getWorkspaceId();
    }

    @Override
    public UUID value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getNickname();
    }

    @Override
    public Object[] value3() {
        return getRoles();
    }

    @Override
    public UUID value4() {
        return getUserId();
    }

    @Override
    public UUID value5() {
        return getWorkspaceId();
    }

    @Override
    public WorkspaceUserRecord value1(UUID value) {
        setId(value);
        return this;
    }

    @Override
    public WorkspaceUserRecord value2(String value) {
        setNickname(value);
        return this;
    }

    @Override
    public WorkspaceUserRecord value3(Object[] value) {
        setRoles(value);
        return this;
    }

    @Override
    public WorkspaceUserRecord value4(UUID value) {
        setUserId(value);
        return this;
    }

    @Override
    public WorkspaceUserRecord value5(UUID value) {
        setWorkspaceId(value);
        return this;
    }

    @Override
    public WorkspaceUserRecord values(UUID value1, String value2, Object[] value3, UUID value4, UUID value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached WorkspaceUserRecord
     */
    public WorkspaceUserRecord() {
        super(WorkspaceUser.WORKSPACE_USER);
    }

    /**
     * Create a detached, initialised WorkspaceUserRecord
     */
    public WorkspaceUserRecord(UUID id, String nickname, Object[] roles, UUID userId, UUID workspaceId) {
        super(WorkspaceUser.WORKSPACE_USER);

        setId(id);
        setNickname(nickname);
        setRoles(roles);
        setUserId(userId);
        setWorkspaceId(workspaceId);
    }
}
